# Generated by Django 3.2.4 on 2021-08-11 06:02

import association.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('venue', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(default='events/event_default.jpg', upload_to=association.models.get_img_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('G', 'General Member'), ('B', 'Board Member'), ('A', 'ADVISOR')], default='G', max_length=1)),
                ('position', models.CharField(blank=True, max_length=25, null=True)),
                ('linkdin_url', models.URLField(blank=True, max_length=100, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=100, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=100, null=True)),
                ('rank', models.IntegerField(default=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
