# Generated by Django 3.2.4 on 2021-08-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='user',
            new_name='users',
        ),
    ]
