# Generated by Django 3.2.4 on 2021-08-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_rename_user_team_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='users',
            new_name='user',
        ),
    ]
