# Generated by Django 3.2.4 on 2021-06-20 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('association', '0002_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.userprofile')),
            ],
            bases=('accounts.userprofile',),
        ),
    ]
