# Generated by Django 3.2.4 on 2021-06-20 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
