# Generated by Django 3.2.4 on 2021-06-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0005_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('G', 'General Member'), ('B', 'Board Member'), ('A', 'ADVISOR')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='team',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='linkdin_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
