# Generated by Django 3.2.4 on 2021-06-22 04:17

import association.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0007_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='events/event_default.jpg', upload_to=association.models.get_img_upload_path),
        ),
    ]
