# Generated by Django 3.2.4 on 2021-07-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blogs/default.jpg', upload_to='blogs/%Y/%m/%d/'),
        ),
    ]
