# Generated by Django 3.2.4 on 2021-06-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_of_subject', models.CharField(max_length=50)),
                ('note_of_semester', models.CharField(max_length=50)),
                ('note_title', models.CharField(max_length=220)),
                ('note_file', models.CharField(max_length=100)),
                ('note_description', models.TextField(blank=True, max_length=200)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_uploaded'],
            },
        ),
    ]
