# Generated by Django 3.2.4 on 2021-06-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_file',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
