# Generated by Django 3.2.4 on 2021-06-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='semester',
            field=models.CharField(choices=[('1', 'First semester'), ('2', 'Second semester'), ('3', 'Third semester'), ('4', 'Fourth semester'), ('5', 'Fifth semester'), ('6', 'Sixth semester'), ('7', 'Seventh semester'), ('8', 'Eighth semester')], max_length=50),
        ),
    ]
